###
GET http://localhost:8080/api/action

###
POST http://localhost:8080/api/action
Content-Type: application/json

{
 "name" : "Pierwsza",
  "organization" : "Szlachetna",
  "description" : "To jest pierwsza testowa",
  "place" : "Kraków"
}